import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { Header } from "@/src/components/organisms/Header";
import { AuthProvider } from "@/src/components/organisms/Auth/AuthProvider";
import dynamic from "next/dynamic";
import { Box, Container, VStack } from "@/panda/jsx";
import { css } from "@/panda/css";
import { Footer } from "@/src/components/organisms/Footer";

export function generateStaticParams() {
  return [{ locale: "en" }];
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  let messages;
  try {
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
            <Box width="full" height="full" overflowY="auto">
              <Header className={css({ height: 16 })} />
              <VStack
                width="full"
                height="calc(100% - 4rem)"
                justifyContent="space-between"
              >
                <Container maxWidth={"breakpoint-xl"} paddingY={6}>
                  {children}
                </Container>
                <Footer />
              </VStack>
            </Box>
          </NextIntlClientProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
